#!/usr/bin/env python3
"""Deterministic startup and mode protocol for observable local session behavior."""

from __future__ import annotations

from pathlib import Path
from typing import Any

PRIVACY_NOTICE = (
    "This local learning partner is not a grader. No course data is sent to a faculty service, "
    "but Codex keeps its normal local chat history. A final local review bundle contains the complete "
    "visible student/advisor conversation, structured work, and final learning review; system and "
    "developer instructions, hidden reasoning, tool calls, and tool output are excluded. Do not enter "
    "credentials, actual salaries, confidential employer information, or sensitive personal information. "
    "Please confirm that you understand and want to continue."
)


def transition(state: dict[str, Any], event: str, payload: Any = None) -> tuple[dict[str, Any], str]:
    current = state.get("state", "NEW")
    if current == "NEW" and event == "START":
        return {"state": "AWAITING_CONSENT", "mode": None}, PRIVACY_NOTICE
    if current == "AWAITING_CONSENT" and event == "CONSENT_YES":
        return {**state, "state": "AWAITING_WBS"}, "Thank you. Upload the approved WBS document generated by Agent 1."
    if current == "AWAITING_CONSENT":
        return state, "I will not request project data until you clearly confirm that you want to continue."
    if current == "AWAITING_WBS" and event == "WBS_NORMALIZED":
        return {**state, "state": "AWAITING_WBS_CONFIRMATION", "wbs_preview": payload}, "I preserved the WBS identifiers and links. Please confirm that this normalized preview is correct."
    if current == "AWAITING_WBS_CONFIRMATION" and event == "WBS_CONFIRMED":
        return {**state, "state": "DRAFTING", "mode": "GUIDED"}, "Guided mode is selected by default. Progress: your approved WBS is confirmed. Next: How would you divide the work into three or four phases using the project checkpoints?"
    if current == "DRAFTING" and event == "SELECT_INDEPENDENT":
        packet = Path(__file__).resolve().parents[1] / "assets" / "independent-mode-packet.md"
        return {**state, "mode": "INDEPENDENT"}, packet.read_text(encoding="utf-8")
    if current == "DRAFTING" and event == "SELECT_GUIDED":
        return {**state, "mode": "GUIDED"}, "Progress: Guided mode is active. Next: Which one phase would you like to define first?"
    if current == "DRAFTING" and event == "FORMAL_REVIEW":
        return state, "Formal review has not run. Say that you are ready for review when your plan is complete."
    if current == "DRAFTING" and event == "READY_FOR_REVIEW":
        return {**state, "state": "FORMAL_REVIEW_REQUESTED"}, "The explicit ready signal is recorded. Run the deterministic formal readiness review now."
    raise ValueError(f"Unsupported protocol transition: {current} + {event}")

